version: "3.8"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    build: ./metro-property-management
    volumes:
      - ./metro-property-management/src:/frontend/src
    environment:
      - WATCHPACK_POLLING=true
  api-server:
    image: api-server
    ports:
      - "3005:3005"
    networks:
      - mern-app
    build: ./property-backend
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - mern-app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
